FROM node:22-alpine

WORKDIR /app

COPY package.json package-lock.json ./
COPY apps/client/package.json apps/client/package.json
COPY apps/server/package.json apps/server/package.json
COPY packages/shared/package.json packages/shared/package.json
COPY packages/game-content/package.json packages/game-content/package.json

RUN npm ci

COPY . .

EXPOSE 3001
EXPOSE 5173
